### ISSUE TITLE
Imagine adding instructions about how to install it

### ISSUE THREAD

**Issue by OBIPPO** [CookiePLMonster/SilentPatchFarCry#5]
Simply Imagine

**Comment by CookiePLMonster** [comment]
ReadMe.txt has installation instructions, although they are an one liner because there is nothing complicated about installing that patch.

On top of that, every release page (Far Cry included) from myself includes a link to [Setup Instructions](https://cookieplmonster.github.io/setup-instructions/). This should be more than enough to figure out how to install.
